config/routes.rb
PlatformJavaApplets::Application.routes.draw do
  resources :applets do
    member do
      get :include
    end
  end
  resources :sessions, :only => [:new, :create]
  match "signout" => "sessions#destroy", :as => :signout
  root :to => 'sessions#new'
  apipie

end

app/models/applet.rb
class Applet < ActiveRecord::Base
  attr_accessible "title", "content", "style", "javascript", "objective", "abstract", "curriculum", "theme", "author", "language", "country", "publisher", "description", "rightsholder", "submiter", "address", "license", "uri", "other_links", "applet_type", "direct_url"

  def include_snippet(width=720, height=400)
    case self.applet_type
    when 'flash'
      <<-EOF
        <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0">
        <param name="src" value="#{self.direct_url}">
        <embed src="#{self.direct_url}" width="#{width}" height="#{height}"></embed>
        </object>
      EOF
    else
      js = <<-EOF
        <script type="text/javascript"  charset="utf-8">
          #{self.javascript.blank? ? "" : self.javascript}
        </script>
      EOF

      style = <<-EOF
        <style>
          #{self.style.blank? ? "" : self.style}
        </style>
      EOF

      content = <<-EOF
        #{self.content}
      EOF

      "#{js} #{style} #{content}"
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :password, :on => :create
  attr_accessible :email, :password, :password_confirmation
  before_create :generate_token

  def generate_token
    self.token ||= (0...8).map{65.+(rand(25)).chr}.join
  end
end

app/controllers/applets_controller.rb
class AppletsController < ApplicationController
  skip_before_filter :ensure_user, :only => :include

  resource_description do
    name "Applets"
    path "/applets"
    formats ['json', 'xml']
    param :token, String, :desc => "The API token.", :required => true
  end

  api :GET, "applets", "Lists created objects"
  def index
    @applets = Applet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @applets }
    end
  end

  api :GET, "applets/:id", "Retreives the applet"
  error :code => 404, :desc => "Not Found"
  param :id, Fixnum, :desc => "Id do objeto de aprendizagem", :required => true
  def show
    @applet = Applet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @applet }
    end
  end

  # GET /applets/new
  # GET /applets/new.json
  def new
    @applet = Applet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @applet }
    end
  end

  # GET /applets/1/edit
  def edit
    @applet = Applet.find(params[:id])
  end

  api :POST, "applets/:id", "Creates the applet"
  error :code => 404, :desc => "Not Found"
  param :applet, Hash do
    param "title", String, :desc => "Object title"
    param "content", String, :desc => "Object HTML"
    param "style", String, :desc => "Object CSS"
    param "javascript", String, :descr => "Object JS"
    param "objective", String
    param "abstract", String
    param "curriculum", String
    param "theme", String
    param "author", String
    param "language", String
    param "country", String
    param "publisher", String
    param "description", String
    param "rightsholder", String
    param "submiter", String
    param "address", String
    param "license", String
    param "uri", String
    param "other_links", String
    param "applet_tyoe", String
    param "direct_url", String
  end
  def create
    @applet = Applet.new(params[:applet])

    respond_to do |format|
      if @applet.save
        format.html { redirect_to @applet, :notice => 'Applet was successfully created.' }
        format.json { render :json => @applet, :status => :created, :location => @applet }
      else
        format.html { render :action => "new" }
        format.json { render :json => @applet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /applets/1
  # PUT /applets/1.json
  def update
    @applet = Applet.find(params[:id])

    respond_to do |format|
      if @applet.update_attributes(params[:applet])
        format.html { redirect_to @applet, :notice => 'Applet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @applet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /applets/1
  # DELETE /applets/1.json
  def destroy
    @applet = Applet.find(params[:id])
    @applet.destroy

    respond_to do |format|
      format.html { redirect_to applets_url }
      format.json { head :no_content }
    end
  end

  def include
    @applet = Applet.find(params[:id])
    @width = params.fetch(:width, 720)
    @height = params.fetch(:height, 340)

    respond_to do |format|
      format.html { render :action => :include, :layout => "clean" }
      format.json { render :json => @applet }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :ensure_user
  helper_method :current_user

  private
  def current_user
     @current_user ||= if user_id = session[:user_id]
      User.find_by_id(user_id)
    elsif token = params[:token]
      User.find_by_token(token)
    end
  end

  def ensure_user
    redirect_to root_url unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :ensure_user, :only => [:new, :create]

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to applets_path, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/helpers/applets_helper.rb
module AppletsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/applets/_form.html.erb
<%= form_for(@applet) do |f| %>
  <% if @applet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@applet.errors.count, "error") %> prohibited this applet from being saved:</h2>

      <ul>
      <% @applet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :applet_type %><br />
    <%= f.text_field :applet_type %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :style %><br />
    <%= f.text_area :style %>
  </div>
  <div class="field">
    <%= f.label :javascript %><br />
    <%= f.text_area :javascript %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/applets/edit.html.erb
<h1>Editing applet</h1>

<%= render 'form' %>

<%= link_to 'Show', @applet %> |
<%= link_to 'Back', applets_path %>

app/views/applets/include.html.erb
<%= @applet.include_snippet(@width, @height).html_safe %>

app/views/applets/index.html.erb
<h1>Listing applets</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Style</th>
    <th>Javascript</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @applets.each do |applet| %>
  <tr>
    <td><%= applet.title %></td>
    <td><%= applet.content %></td>
    <td><%= applet.style %></td>
    <td><%= applet.javascript %></td>
    <td><%= link_to 'Show', applet %></td>
    <td><%= link_to 'Edit', edit_applet_path(applet) %></td>
    <td><%= link_to 'Destroy', applet, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Applet', new_applet_path %>

app/views/applets/new.html.erb
<h1>New applet</h1>

<%= render 'form' %>

<%= link_to 'Back', applets_path %>

app/views/applets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @applet.title %>
</p>

<p>
  <b>Applet type:</b>
  <%= @applet.applet_type %>
</p>

<p>
  <b>Content:</b>
  <%= @applet.include_snippet(@width, @height).html_safe %>
</p>

<p>
  <b>Style:</b>
  <script type="text/javascript"  charset="utf-8">
    <%= @applet.javascript.html_safe  %>
  </script>
</p>

<p>
  <b>Javascript:</b>
   <style>
    <!--
      <%= @applet.style.html_safe %>
    -->
   </style>
</p>


<%= link_to 'Edit', edit_applet_path(@applet) %> |
<%= link_to 'Back', applets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlatformJavaApplets</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
  <%= link_to "Sair", signout_path %>
<% else %>
  <%= link_to "Entrar", new_session_path %>
<% end %>
<%= yield %>

</body>
</html>

app/views/layouts/clean.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlatformJavaApplets</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>